### ISSUE TITLE
CLIENT: src/main.jsx

### ISSUE THREAD

**Issue by c-phelps** [c-phelps/MemorEase#14]
Set up the main.jsx file to handle front end routing via react-router-dom, use the wireframe in the doc in slack for reference to pages we will need for children of browser router:
- Route - Page
-index - Home (landing page)
-'/login' - Login
-'/signup' - Signup
-'/decks' - Decks
-'/collection/id' - Collection
-'/createdeck' - Createdeck

**Comment by Ashleighjg** [comment]
Pull Request https://github.com/c-phelps/MemorEase/pull/35
