### ISSUE TITLE
PROJECT: decide on a color scheme for the project

### ISSUE THREAD

**Issue by c-phelps** [c-phelps/MemorEase#24]
title

**Comment by Ashleighjg** [comment]
Cool and Professional Color Scheme

Balanced and professional, this is ideal for an educational app where clean and cool tones create a focused study space.

- Primary: Indigo (#5C6BC0)
- Secondary: Steel Gray (#90A4AE)
- Accent: Seafoam (#81C784)
- Text: Gunmetal (#263238)
- Background: Soft White (#FAFAFA)

[Color wheel - color theory and calculator _ Canva Colors.pdf](https://github.com/user-attachments/files/17594824/Color.wheel.-.color.theory.and.calculator._.Canva.Colors.pdf)

![Image](https://github.com/user-attachments/assets/54fe9e5c-4636-4260-8037-11ee37e7eecf)
