### ISSUE TITLE
CLIENT: Implement color scheme from issue #24

### ISSUE THREAD

**Issue by c-phelps** [c-phelps/MemorEase#43]
Implement the color scheme from issue #24 using custom CSS or Chakra UI
Create CSS variables for each of the colors and some classes that can be called to use those colors for different values.

Primary: Indigo (#5C6BC0)
Secondary: Steel Gray (#90A4AE)
Accent: Seafoam (#81C784)
Text: Gunmetal (#263238)
Background: Soft White (#FAFAFA)
[Color wheel - color theory and calculator _ Canva Colors.pdf](https://github.com/user-attachments/files/17594824/Color.wheel.-.color.theory.and.calculator._.Canva.Colors.pdf)
![Image](https://github.com/user-attachments/assets/4ec0ff28-1259-4cd5-bea0-1b2f51c6f7fd)

**Comment by AndrewBrown77** [comment]
https://github.com/c-phelps/MemorEase/pull/73

**Comment by Ashleighjg** [comment]
pull request https://github.com/c-phelps/MemorEase/pull/76
