### ISSUE TITLE
CLIENT: Update Header/Navbar - see description

### ISSUE THREAD

**Issue by c-phelps** [c-phelps/MemorEase#51]
Update Navbar/Header to:

- Match naming scheme (uppercase N in file name)
- Navbar formatted to align on the right side of the screen
- Header/title formatted to align on the left side of the screen next to logo
- Conditionally to not load when on the home page
- when logout clicked, be ready to handle log out functionality and redirect user to the home page 
expected layout
 ![Image](https://github.com/user-attachments/assets/311be628-9f0b-4209-a751-77ea892c225f)

**Comment by AndrewBrown77** [comment]
https://github.com/c-phelps/MemorEase/pull/68
