### ISSUE TITLE
SERVER: Update the typeDefs and resolvers for Delete Deck and Rename Deck

### ISSUE THREAD

**Issue by c-phelps** [c-phelps/MemorEase#59]
Update typeDefs to handle mutations for:
Delete Deck
Rename Deck

Update resolvers.js to handle necessary mutations:
Delete Deck
Rename Deck

**Comment by Ashleighjg** [comment]
Pull Request https://github.com/c-phelps/MemorEase/pull/63

**Comment by Ashleighjg** [comment]
Pull Request https://github.com/c-phelps/MemorEase/pull/64
