### ISSUE TITLE
Review potential technologies for us to use

### ISSUE THREAD

**Issue by c-phelps** [c-phelps/MemorEase#6]
Take a look at suggested technologies and pick one or two for us to incorporate:
https://styled-components.com/docs/basics#getting-started
https://emotion.sh/docs/introduction
https://semantic-ui.com/
https://chakra-ui.com/
https://ant.design/

**Comment by Megannx** [comment]
I recommend using Chakra UI as our primary CSS integration source. It offers straightforward implementation with comprehensive instructions, making it easy to get started. Chakra UI is highly responsive and provides a wide range of options for visual components, which will enhance the overall design of our webpage.

For our second option, if we want to incorporate more personalized and custom CSS alongside Chakra UI, Styled Components is a great choice. It allows for better customization and dynamic styling, providing users with a more engaging experience.
